import Link from "next/link";

import type { PublicStoryArchive, PublicStoryItem } from "@/features/content/server/public-media-content-service";
import { PhotographyHeader } from "@/features/photography/components/photography-header";

export function StoryArchive({ archive }: { archive: PublicStoryArchive }) {
  return <main className="min-h-dvh bg-[#111111] text-[#f7f7f7]"><PhotographyHeader /><section className="mx-auto w-full max-w-7xl px-5 pb-20 pt-12 sm:px-8 lg:px-12 lg:pt-20"><div className="grid gap-8 border-b border-[#303030] pb-10 lg:grid-cols-[1fr_22rem] lg:items-end"><div><p className="font-mono text-[0.7rem] text-[#979797]">STORIES / PRIVATE NOTES</p><h1 className="mt-4 font-[family-name:var(--font-editorial)] text-5xl leading-[1.02] sm:text-7xl">把相遇写成故事。</h1></div><p className="max-w-sm text-sm leading-7 text-[#a8a8a8]">关于恋爱、时间和一起走过的地方。正文以安全 Markdown 保存与展示。</p></div>{archive.items.length ? <div className="mt-8 divide-y divide-[#303030] border-y border-[#303030]">{archive.items.map((item, index) => <StoryCard index={index} item={item} key={item.id} />)}</div> : <div className="grid min-h-64 place-items-center border-b border-[#303030] py-12 text-center"><div><p className="font-[family-name:var(--font-editorial)] text-3xl">等待一段故事。</p><p className="mt-3 text-sm text-[#9b9b9b]">管理员发布故事后，它会出现在这里。</p></div></div>}</section></main>;
}

function StoryCard({ item, index }: { item: PublicStoryItem; index: number }) { return <article><Link className="grid gap-4 py-6 transition-colors hover:bg-[#171717] sm:grid-cols-[5rem_1fr_auto] sm:items-center sm:px-4" href={`/stories/${item.slug}`}><p className="font-mono text-xs text-[#777777]">{String(index + 1).padStart(2, "0")}</p><div><p className="font-mono text-[0.65rem] text-[#929292]">{formatDate(item.publishedAt)}</p><h2 className="mt-2 font-[family-name:var(--font-editorial)] text-3xl leading-tight">{item.title}</h2>{item.excerpt ? <p className="mt-2 max-w-2xl text-sm leading-6 text-[#9d9d9d]">{item.excerpt}</p> : null}</div><p className="font-mono text-[0.65rem] text-[#a8a8a8]">READ / OPEN</p></Link></article>; }
function formatDate(value: string) { return new Intl.DateTimeFormat("zh-CN", { year: "numeric", month: "2-digit", day: "2-digit" }).format(new Date(value)); }
